# Generated by Django 3.2 on 2022-08-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ФИО клиента')),
                ('citizenship', models.CharField(blank=True, default='Кыргызстан', max_length=20, verbose_name='гражданство')),
                ('birth_day', models.DateField(verbose_name='год рождения')),
                ('work_place', models.CharField(blank=True, max_length=30, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
