# Generated by Django 3.2 on 2022-08-02 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Номер аккаунта')),
                ('account_type', models.IntegerField(default=1, verbose_name='Тип аккаунта')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'db_table': 'accounts',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_day',
            field=models.DateField(verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='citizenship',
            field=models.CharField(blank=True, default='Кыргызстан', max_length=20, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='client',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обновление'),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_place',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Место работы'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='customers',
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Cумма кредита')),
                ('date', models.DateField(default=datetime.date(2022, 8, 2), verbose_name='Дата получение кредита')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.account', verbose_name='Cчет')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
                'db_table': 'loans',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.client', verbose_name='Клиент'),
        ),
    ]
