# Generated by Django 3.2 on 2022-08-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20220802_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='citizenship',
            field=models.CharField(default='Кыргызстан', max_length=20, verbose_name='Гражданство'),
        ),
    ]
